package web

// ActionButton represents a suggested follow-up action for the user.
// These are generated by analyzing agent messages for questions or prompts.
type ActionButton struct {
	// Label is the button text displayed to the user (max 50 chars)
	Label string `json:"label"`
	// Response is the text that will be sent if the user clicks the button (max 1000 chars)
	Response string `json:"response"`
}
