package web

import (
	"context"

	"github.com/coder/acp-go-sdk"
	"github.com/inercia/mitto/internal/session"
)

// PlanEntry represents a single task in the agent's execution plan.
// This mirrors the ACP protocol's PlanEntry structure.
type PlanEntry struct {
	// Content is a human-readable description of what this task aims to accomplish.
	Content string `json:"content"`
	// Priority indicates the relative importance of this task (high, medium, low).
	Priority string `json:"priority"`
	// Status is the current execution status (pending, in_progress, completed).
	Status string `json:"status"`
}

// SessionObserver defines the interface for receiving session events.
// This allows multiple clients (WebSocket connections) to observe a single session.
//
// Events that are persisted include a sequence number (seq) for ordering and deduplication.
// The seq is assigned when the event is received from the ACP, ensuring streaming and
// persisted events have the same seq. Clients can use seq to:
// - Deduplicate events (same session_id + seq = same event)
// - Order events correctly after reconnection
// - Track which events they've seen for sync requests
type SessionObserver interface {
	// OnAgentMessage is called when the agent sends a message chunk (HTML).
	// seq is the sequence number for this logical message (chunks of the same message share the same seq).
	OnAgentMessage(seq int64, html string)

	// OnAgentThought is called when the agent sends a thought chunk (plain text).
	// seq is the sequence number for this logical thought (chunks share the same seq).
	OnAgentThought(seq int64, text string)

	// OnToolCall is called when a tool call starts.
	// seq is the sequence number for this tool call event.
	OnToolCall(seq int64, id, title, status string)

	// OnToolUpdate is called when a tool call status is updated.
	// seq is the sequence number for this tool update event.
	OnToolUpdate(seq int64, id string, status *string)

	// OnPlan is called when a plan update occurs.
	// seq is the sequence number for this plan event.
	// entries contains the list of plan tasks with their status.
	OnPlan(seq int64, entries []PlanEntry)

	// OnFileWrite is called when a file is written.
	// seq is the sequence number for this file write event.
	OnFileWrite(seq int64, path string, size int)

	// OnFileRead is called when a file is read.
	// seq is the sequence number for this file read event.
	OnFileRead(seq int64, path string, size int)

	// OnPermission is called when a permission request needs user input.
	// Only the first observer to respond will have their answer used.
	OnPermission(ctx context.Context, params acp.RequestPermissionRequest) (acp.RequestPermissionResponse, error)

	// OnPromptComplete is called when a prompt response is complete.
	// eventCount is the current total event count for the session (for sync tracking).
	OnPromptComplete(eventCount int)

	// OnActionButtons is called when follow-up suggestions have been generated.
	// This is called asynchronously after OnPromptComplete, generated by the auxiliary
	// conversation analyzing the agent's response for questions or follow-up prompts.
	OnActionButtons(buttons []ActionButton)

	// OnUserPrompt is called when a user sends a prompt.
	// This is broadcast to all observers so they can update their UI.
	// senderID identifies which observer sent the prompt (for deduplication).
	// promptID is the client-generated ID for delivery confirmation.
	// imageIDs contains IDs of any attached images.
	// fileIDs contains IDs of any attached files.
	// seq is the sequence number for this user prompt event.
	OnUserPrompt(seq int64, senderID, promptID, message string, imageIDs, fileIDs []string)

	// OnError is called when an error occurs.
	OnError(message string)

	// OnQueueUpdated is called when the message queue state changes.
	// action is one of: "added", "removed", "cleared"
	OnQueueUpdated(queueLength int, action string, messageID string)

	// OnQueueReordered is called when the queue order changes.
	// messages contains the full updated list of queued messages in their new order.
	OnQueueReordered(messages []session.QueuedMessage)

	// OnQueueMessageSending is called when a queued message is about to be sent.
	OnQueueMessageSending(messageID string)

	// OnQueueMessageSent is called after a queued message was delivered.
	OnQueueMessageSent(messageID string)

	// OnAvailableCommandsUpdated is called when the agent sends available slash commands.
	// Commands are sent shortly after session creation and may be updated during the session.
	OnAvailableCommandsUpdated(commands []AvailableCommand)

	// OnACPStopped is called when the ACP connection for this session is stopped.
	// This happens when the session is archived or explicitly closed.
	// reason indicates why the session was stopped (e.g., "archived", "archived_timeout").
	// Observers should update their state to prevent further prompts.
	OnACPStopped(reason string)
}
