run:
  timeout: 5m

issues:
  exclude-dirs:
    - cmd/mitto-app  # macOS-specific, requires cgo and webview
  exclude-dirs-use-default: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

