run:
  timeout: 5m
  skip-dirs:
    - cmd/mitto-app  # macOS-specific, requires cgo and webview

linters:
  disable:
    - errcheck  # TODO: fix unchecked error returns

issues:
  exclude-dirs:
    - cmd/mitto-app

