run:
  timeout: 5m
  build-tags:
    - ""
  skip-dirs:
    - cmd/mitto-app  # macOS-specific, requires cgo and webview

issues:
  exclude-dirs:
    - cmd/mitto-app  # macOS-specific, requires cgo and webview

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

