/**
 * UI responsiveness benchmark (mitto-sus.1.2): DOM size and scroll-jank cost
 * as conversation history grows (small / medium / max).
 *
 * Self-seeding: `test.beforeAll` builds (if needed) and runs the
 * `seed-perf-history` Go helper, which writes sessions directly into the
 * live session store (bypassing ACP/UI entirely, so seeding thousands of
 * messages doesn't burn test time) — the same "write directly into the
 * store" technique tests/ui/helpers/create-hierarchical-sessions.go uses for
 * parent/child fixtures. Content comes from the deterministic snapshots
 * generated by scripts/gen-perf-histories.mjs (committed under
 * tests/ui/perf/fixtures/histories/). Safe to run repeatedly: each run seeds
 * fresh sessions with newly generated IDs.
 *
 * If the Go toolchain is unavailable or the build/seed step fails, the test
 * skips rather than failing the suite (mirrors the graceful-skip pattern in
 * hierarchical-sessions.spec.ts for its own out-of-band helper).
 *
 * Smoke test of DOM/frame collectors against real large payloads, not a hard
 * performance gate — see docs/devel/ui-responsiveness-benchmarks.md.
 */
import { test, expect } from "../../fixtures/test-fixtures";
import * as path from "path";
import * as fs from "fs";
import { fileURLToPath } from "url";
import { execFileSync } from "child_process";
import {
  enablePerf,
  collectDOMStats,
  collectFrameStats,
  writePerfSample,
} from "../../utils/perf";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SIZES = ["small", "medium", "max"] as const;
const repoRoot = path.resolve(__dirname, "../../../..");
const mittoDir = process.env.MITTO_DIR || "/tmp/mitto-test";
const markerFile = path.join(mittoDir, "perf-history-sessions.json");

let seedingAvailable = false;

test.describe("Perf: history-size load cost", () => {
  test.describe.configure({ mode: "serial" });
  test.setTimeout(120_000);

  test.beforeAll(() => {
    try {
      const binPath = path.join(mittoDir, "seed-perf-history-bin");
      execFileSync(
        "go",
        ["build", "-o", binPath, "./tests/ui/helpers/seed-perf-history"],
        { cwd: repoRoot, stdio: "pipe" },
      );
      execFileSync(
        binPath,
        [
          "-dir",
          mittoDir,
          "-snapshots-dir",
          path.join(repoRoot, "tests/ui/perf/fixtures/histories"),
          "-working-dir",
          path.join(repoRoot, "tests/fixtures/workspaces/project-alpha"),
        ],
        { stdio: "pipe" },
      );
      seedingAvailable = fs.existsSync(markerFile);
    } catch (err) {
      console.log(`[Test] Could not seed perf histories, will skip: ${err}`);
      seedingAvailable = false;
    }
  });

  test("reports DOM node count and scroll frame stats for small/medium/max histories", async ({
    page,
    helpers,
  }) => {
    if (!seedingAvailable) {
      console.log(
        "[Test] Skipping: seed-perf-history build/run failed (see beforeAll log above)",
      );
      test.skip();
      return;
    }

    const sessionIds: Record<string, string> = JSON.parse(
      fs.readFileSync(markerFile, "utf-8"),
    );

    await enablePerf(page);
    await helpers.navigateAndWait(page);

    let prevDomNodes = 0;
    for (const size of SIZES) {
      const sessionId = sessionIds[size];
      if (!sessionId) {
        console.log(`[Test] No seeded session for "${size}", skipping this size`);
        continue;
      }

      await page.evaluate(
        (id) => localStorage.setItem("mitto_last_session_id", id),
        sessionId,
      );
      await page.reload();
      await helpers.waitForAppReady(page);
      await page.waitForTimeout(300);

      const domStats = await collectDOMStats(page);
      expect(domStats.domNodes).toBeGreaterThan(0);

      const container = page.locator("body");
      await container.evaluate((el) => el.scrollBy(0, -el.scrollHeight));
      const frameStats = await collectFrameStats(page, 1000);

      // eslint-disable-next-line no-console
      console.log(
        `[perf] history-load "${size}": domNodes=${domStats.domNodes} ` +
          `heapBytes=${domStats.usedJSHeapBytes ?? "n/a"} ` +
          `scrollFps=${frameStats.fps.toFixed(1)} missedFrames=${frameStats.missedFrames}`,
      );
      // mitto-sus.1.3 row 7 ("DOM node count per 1 000 rendered messages"):
      // **record-only** per the bead description — no hard budget yet.
      writePerfSample(`history-load.${size}`, "domNodes", domStats.domNodes);
      if (domStats.usedJSHeapBytes !== null) {
        writePerfSample(
          `history-load.${size}`,
          "usedJSHeapBytes",
          domStats.usedJSHeapBytes,
        );
      }

      // DOM node count should not shrink as history size grows (monotonic-by-size).
      expect(domStats.domNodes).toBeGreaterThanOrEqual(prevDomNodes);
      prevDomNodes = domStats.domNodes;
    }
  });
});
