/**
 * UI responsiveness benchmark (mitto-sus.1.2, extended by mitto-sus.8): DOM
 * size and scroll-jank cost as conversation history grows (small / medium /
 * max), PLUS DOM/layout/paint growth as the user pages back through history
 * via "Load earlier messages" (prepend).
 *
 * Self-seeding: `test.beforeAll` builds (if needed) and runs the
 * `seed-perf-history` Go helper, which writes sessions directly into the
 * live session store (bypassing ACP/UI entirely, so seeding thousands of
 * messages doesn't burn test time) — the same "write directly into the
 * store" technique tests/ui/helpers/create-hierarchical-sessions.go uses for
 * parent/child fixtures. Content comes from the deterministic snapshots
 * generated by scripts/gen-perf-histories.mjs (committed under
 * tests/ui/perf/fixtures/histories/). Safe to run repeatedly: each run seeds
 * fresh sessions with newly generated IDs.
 *
 * If the Go toolchain is unavailable or the build/seed step fails, the test
 * skips rather than failing the suite (mirrors the graceful-skip pattern in
 * hierarchical-sessions.spec.ts for its own out-of-band helper).
 *
 * Smoke test of DOM/frame collectors against real large payloads, not a hard
 * performance gate — see docs/devel/ui-responsiveness-benchmarks.md.
 *
 * mitto-sus.8 fix: the initial-load measurement used to follow a fixed
 * `page.waitForTimeout(300)` after reload, which is a race against the
 * WebSocket reconnect + `load_events` round trip — under CI load this can
 * fire BEFORE any message renders, so all three sizes were measuring the
 * same near-empty app shell (explains the previously-identical
 * `domNodes=578` baseline rows for small/medium/max). Replaced with a
 * deterministic wait on the actual rendered user-message count. This also
 * surfaces the real architectural fact the spike needed to measure: initial
 * DOM size is capped by `INITIAL_EVENTS_LIMIT` (50 events / session — see
 * web/static/lib.js), not by total history size, so medium and max render
 * near-identical DOM on first paint; growth only happens once the user pages
 * back via "Load earlier messages" (prepend), which is now measured below.
 */
import { test, expect } from "../../fixtures/test-fixtures";
import * as path from "path";
import * as fs from "fs";
import { fileURLToPath } from "url";
import { execFileSync } from "child_process";
import {
  enablePerf,
  collectDOMStats,
  collectFrameStats,
  collectPaintLayoutStats,
  writePerfSample,
} from "../../utils/perf";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SIZES = ["small", "medium", "max"] as const;
const repoRoot = path.resolve(__dirname, "../../../..");
const mittoDir = process.env.MITTO_DIR || "/tmp/mitto-test";
const markerFile = path.join(mittoDir, "perf-history-sessions.json");

// Mirrors scripts/gen-perf-histories.mjs's (name, message count) table, so
// the spec can compute how many user messages should render initially
// without re-parsing the snapshot files.
const SIZE_MESSAGE_COUNTS: Record<(typeof SIZES)[number], number> = {
  small: 10,
  medium: 1000,
  max: 5000,
};

// Mirrors web/static/lib.js's INITIAL_EVENTS_LIMIT (not imported: that
// module touches browser globals at parse time, so UI perf specs keep a
// local mirror — same pattern gen-perf-histories.mjs uses for its own
// "no exported MAX_HISTORY constant" cap comment above).
const INITIAL_EVENTS_LIMIT = 50;

// Bounded number of "Load earlier messages" clicks to measure per size.
// Not exhaustive (max could page back ~50 times before MAX_MESSAGES=1000
// caps further loads) — enough to establish a growth trend without making
// the spec slow.
const PREPEND_STEPS = 4;

let seedingAvailable = false;

test.describe("Perf: history-size load cost", () => {
  test.describe.configure({ mode: "serial" });
  test.setTimeout(120_000);

  test.beforeAll(() => {
    try {
      const binPath = path.join(mittoDir, "seed-perf-history-bin");
      execFileSync(
        "go",
        ["build", "-o", binPath, "./tests/ui/helpers/seed-perf-history"],
        { cwd: repoRoot, stdio: "pipe" },
      );
      execFileSync(
        binPath,
        [
          "-dir",
          mittoDir,
          "-snapshots-dir",
          path.join(repoRoot, "tests/ui/perf/fixtures/histories"),
          "-working-dir",
          path.join(repoRoot, "tests/fixtures/workspaces/project-alpha"),
        ],
        { stdio: "pipe" },
      );
      seedingAvailable = fs.existsSync(markerFile);
    } catch (err) {
      console.log(`[Test] Could not seed perf histories, will skip: ${err}`);
      seedingAvailable = false;
    }
  });

  test("reports DOM node count and scroll frame stats for small/medium/max histories", async ({
    page,
    helpers,
    selectors,
    timeouts,
  }) => {
    if (!seedingAvailable) {
      console.log(
        "[Test] Skipping: seed-perf-history build/run failed (see beforeAll log above)",
      );
      test.skip();
      return;
    }

    const sessionIds: Record<string, string> = JSON.parse(
      fs.readFileSync(markerFile, "utf-8"),
    );

    await enablePerf(page);
    await helpers.navigateAndWait(page);

    let prevDomNodes = 0;
    for (const size of SIZES) {
      const sessionId = sessionIds[size];
      if (!sessionId) {
        console.log(`[Test] No seeded session for "${size}", skipping this size`);
        continue;
      }

      await page.evaluate(
        (id) => localStorage.setItem("mitto_last_session_id", id),
        sessionId,
      );
      await page.reload();
      await helpers.waitForAppReady(page);

      // Deterministic wait (mitto-sus.8 fix — see file header): wait for the
      // actual rendered user-message count instead of a fixed timeout, which
      // used to race the WebSocket reconnect + load_events round trip.
      const totalMessages = SIZE_MESSAGE_COUNTS[size];
      const expectedUserMessages = Math.min(
        Math.floor(totalMessages / 2),
        Math.floor(INITIAL_EVENTS_LIMIT / 2),
      );
      await helpers.waitForMessagesLoaded(page, expectedUserMessages);

      const domStats = await collectDOMStats(page);
      expect(domStats.domNodes).toBeGreaterThan(0);

      const container = page.locator("body");
      await container.evaluate((el) => el.scrollBy(0, -el.scrollHeight));
      const frameStats = await collectFrameStats(page, 1000);

      // eslint-disable-next-line no-console
      console.log(
        `[perf] history-load "${size}": domNodes=${domStats.domNodes} ` +
          `heapBytes=${domStats.usedJSHeapBytes ?? "n/a"} ` +
          `scrollFps=${frameStats.fps.toFixed(1)} missedFrames=${frameStats.missedFrames}`,
      );
      // mitto-sus.1.3 row 7 ("DOM node count per 1 000 rendered messages"):
      // **record-only** per the bead description — no hard budget yet.
      writePerfSample(`history-load.${size}`, "domNodes", domStats.domNodes);
      if (domStats.usedJSHeapBytes !== null) {
        writePerfSample(
          `history-load.${size}`,
          "usedJSHeapBytes",
          domStats.usedJSHeapBytes,
        );
      }

      // DOM node count should not shrink as history size grows (monotonic-by-size).
      expect(domStats.domNodes).toBeGreaterThanOrEqual(prevDomNodes);
      prevDomNodes = domStats.domNodes;

      // mitto-sus.8: measure DOM/layout/paint growth + latency as the user
      // pages back through history via "Load earlier messages" (prepend).
      // This is where unbounded DOM growth actually happens (up to
      // MAX_MESSAGES=1000, see web/static/lib.js) — the initial-load
      // measurement above is capped by INITIAL_EVENTS_LIMIT regardless of
      // total history size.
      let prevStepDomNodes = domStats.domNodes;
      for (let step = 0; step < PREPEND_STEPS; step++) {
        const limitReached = page.locator(
          '[data-testid="limit-reached-indicator"]',
        );
        const loadMoreButton = page.locator(
          '[data-testid="load-more-button"]',
        );
        if (await limitReached.isVisible().catch(() => false)) break;
        if (!(await loadMoreButton.isVisible().catch(() => false))) break;

        const beforeCount = await page.locator(selectors.userMessage).count();
        const beforePaint = await collectPaintLayoutStats(page);
        const t0 = Date.now();
        await loadMoreButton.click();
        await expect(page.locator(selectors.userMessage)).not.toHaveCount(
          beforeCount,
          { timeout: timeouts.appReady },
        );
        const latencyMs = Date.now() - t0;
        const afterPaint = await collectPaintLayoutStats(page);
        const stepDomStats = await collectDOMStats(page);

        // eslint-disable-next-line no-console
        console.log(
          `[perf] history-load "${size}" prepend-step ${step}: ` +
            `domNodes=${stepDomStats.domNodes} latencyMs=${latencyMs}`,
        );
        writePerfSample(
          `history-load.${size}.prepend-step-${step}`,
          "domNodes",
          stepDomStats.domNodes,
        );
        writePerfSample(
          `history-load.${size}.prepend-step-${step}`,
          "latencyMs",
          latencyMs,
        );
        if (beforePaint && afterPaint) {
          writePerfSample(
            `history-load.${size}.prepend-step-${step}`,
            "layoutDeltaMs",
            afterPaint.layoutMs - beforePaint.layoutMs,
          );
          writePerfSample(
            `history-load.${size}.prepend-step-${step}`,
            "paintDeltaMs",
            afterPaint.paintMs - beforePaint.paintMs,
          );
        }

        // DOM should never shrink as more history is prepended.
        expect(stepDomStats.domNodes).toBeGreaterThanOrEqual(
          prevStepDomNodes,
        );
        prevStepDomNodes = stepDomStats.domNodes;
      }
    }
  });
});
