#!/usr/bin/env node
// mitto-sus.2: aggregates the Chromium/WebKit/WKWebView legs of the UI
// responsiveness A/B profile into one comparative Markdown table with
// engine and wrapper ratios. Reuses scripts/perf-summary.mjs's
// aggregateResults() for the WKWebView leg (a raw results/<runId>/ dir
// populated by the manual playbook — see
// docs/devel/ui-responsiveness-benchmarks.md) and reads committed baseline
// JSON directly for the Chromium/WebKit legs.
//
// Usage:
//   node scripts/perf-ab.mjs
//       [--chromium <baseline.json>]   default: tests/ui/perf/baseline.json
//       [--webkit <baseline.json>]     default: tests/ui/perf/baseline-webkit.json
//       [--wkwebview <results-dir>]    default: tests/ui/perf/results/latest-wkwebview
//       [--out <md-path>]              default: tests/ui/perf/results/latest/ab-report.md
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { aggregateResults } from "./perf-summary.mjs";

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const key = argv[i];
    if (!key.startsWith("--")) continue;
    const name = key.slice(2);
    const value = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : "true";
    args[name] = value;
  }
  return args;
}

function loadBaselineSamples(path) {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf-8")).samples ?? {};
  } catch {
    return null;
  }
}

/** ratio = current/base, or null if either side is missing/zero-base. */
function ratio(current, base) {
  if (typeof current !== "number" || typeof base !== "number" || base === 0) return null;
  return current / base;
}

/** Cross-joins scenario/metric keys across the three legs into ratio rows. */
export function buildComparison(chromium, webkit, wkwebview) {
  const scenarios = new Set([
    ...Object.keys(chromium ?? {}),
    ...Object.keys(webkit ?? {}),
    ...Object.keys(wkwebview ?? {}),
  ]);
  const rows = [];
  for (const scenario of [...scenarios].sort()) {
    const metrics = new Set([
      ...Object.keys(chromium?.[scenario] ?? {}),
      ...Object.keys(webkit?.[scenario] ?? {}),
      ...Object.keys(wkwebview?.[scenario] ?? {}),
    ]);
    for (const metric of [...metrics].sort()) {
      if (metric === "n") continue;
      const c = chromium?.[scenario]?.[metric];
      const w = webkit?.[scenario]?.[metric];
      const n = wkwebview?.[scenario]?.[metric];
      rows.push({
        scenario,
        metric,
        chromium: c,
        webkit: w,
        wkwebview: n,
        webkitOverChromium: ratio(w, c),
        wkwebviewOverWebkit: ratio(n, w),
      });
    }
  }
  return rows;
}

function fmt(v) {
  return typeof v === "number" ? v.toFixed(2) : "—";
}

function fmtRatio(v) {
  return typeof v === "number" ? `${v.toFixed(2)}x` : "—";
}

export function renderReport(rows) {
  const lines = [];
  lines.push("# UI Responsiveness A/B Report (mitto-sus.2)");
  lines.push("");
  lines.push(
    "Auto-generated by `make bench-ui-ab` from the Chromium baseline " +
      "(`tests/ui/perf/baseline.json`), the WebKit baseline " +
      "(`tests/ui/perf/baseline-webkit.json`), and the WKWebView manual-playbook " +
      "results (`tests/ui/perf/results/latest-wkwebview/`). `webkit/chromium` " +
      "isolates the rendering engine; `wkwebview/webkit` isolates the native " +
      "wrapper. Do not edit by hand — re-run `make bench-ui-ab` to refresh.",
  );
  lines.push("");
  lines.push(
    "| Scenario | Metric | Chromium | WebKit | WKWebView | WebKit/Chromium | WKWebView/WebKit |",
  );
  lines.push("|---|---|---|---|---|---|---|");
  for (const r of rows) {
    lines.push(
      `| ${r.scenario} | ${r.metric} | ${fmt(r.chromium)} | ${fmt(r.webkit)} | ` +
        `${fmt(r.wkwebview)} | ${fmtRatio(r.webkitOverChromium)} | ${fmtRatio(r.wkwebviewOverWebkit)} |`,
    );
  }
  lines.push("");
  lines.push(
    "Chromium-only metrics (CDP-based `PaintLayoutStats`, `usedJSHeapBytes`) " +
      "are `—` on the WebKit/WKWebView legs by design — see " +
      "[ui-responsiveness-benchmarks.md](../../../../../docs/devel/ui-responsiveness-benchmarks.md) " +
      "(default output path: tests/ui/perf/results/latest/ab-report.md).",
  );
  lines.push("");
  return lines.join("\n");
}

export function main() {
  const args = parseArgs(process.argv.slice(2));
  const chromiumPath = resolve(args.chromium ?? "tests/ui/perf/baseline.json");
  const webkitPath = resolve(args.webkit ?? "tests/ui/perf/baseline-webkit.json");
  const wkwebviewDir = resolve(args.wkwebview ?? "tests/ui/perf/results/latest-wkwebview");
  const outPath = resolve(args.out ?? "tests/ui/perf/results/latest/ab-report.md");

  const chromium = loadBaselineSamples(chromiumPath);
  const webkit = loadBaselineSamples(webkitPath);
  const wkwebview = aggregateResults(wkwebviewDir);

  if (!chromium) {
    console.error(
      `no Chromium baseline found at ${chromiumPath} — run make bench-ui-baseline first`,
    );
    process.exit(1);
  }

  const rows = buildComparison(chromium, webkit, wkwebview);
  const report = renderReport(rows);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, report);
  console.log(`wrote A/B report: ${outPath}`);
}

if (resolve(fileURLToPath(import.meta.url)) === resolve(process.argv[1] ?? "")) {
  main();
}
